DEFAULT_ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24 * 8
DEFAULT_SECRET_KEY = "do-not-use-this-in-production"
DEFAULT_LEGION_HASH_SCHEME = "pbkdf2_sha512"
DEFAULT_ACCEPTED_JWT_DECODE_ALGS = ["HS256"]
DEFAULT_JWT_ENCODING_ALG = "HS256"
DEFAULT_LOGIN_ROUTE = "/login"
DEFAULT_LOGIN_ROUTE_TAGS = ["login"]

